### PR TITLE
Includes reorganization (on additional_fixes)

### PR DESCRIPTION
**Pull request by valco1994**
* All source code files were rewritten to use conditional compilation on the base of headers/functions presence instead of platform-macro passing
* Also the problem with `pid_t` was solved (see issue #55)

### CODE REVIEW

**Comment by eyalroz** [comment]
So, this causes warnings when building on my system after a merge. Looking into it now.

**Comment by eyalroz** [comment]
Ok, it seems like we needed to keep the _POSIX_C_SOURCE definitions for clang and GCC which you had removed. Let's see if this builds...

**Comment by eyalroz** [comment]
@valco1994 : Tell me - did you make sure that the MSVC build was concluding with no errors and no warnings?

**Comment by valco1994** [comment]
I make sure that MSVC build was concluding with no errors and built code was working successfully. I don't remember what was happening with warnings.

**Comment by eyalroz** [comment]
Ok, this is my fault - I should have I asked earlier. I'm aiming for 0 warnings. Ok, still a bit of work left then. You can have a look at the `additional_fixes` branch now - it's had more commits, some of them are intended to address the warnings. You can also check out the Issues page.

**Comment by eyalroz** [comment]
Oh, one more thing: In `text.c` we now have:
```
#if (defined(HAVE_UNISTD_H) && defined(HAVE_SYS_WAIT_H)) // POSIX-compatible system
//#include <unistd.h>
//#include <sys/wait.h>
#elif (defined(HAVE_PROCESS_H) && defined(HAVE_WINDOWS_H)) // Windows system
```
Why are the two includes commented-out? Or rather - it seems we don't do any waiting or process control in this file. So should we remove these lines? What about the Windows' `<process.h>` include?

**Comment by valco1994** [comment]
I only change condition here. Probably we should delete whole `#if ... #endif` construction

**Pull request merged**
